# It's very important not to use TAB characters in this file
# Use two spaces instead of a TAB
# week_starts is the day you want the calendar to display first (0=Sunday, 1=Monday etc.)
# hp_completed is the number of completed items you want displayed on the home page
# staleness_starts is the number of days before actions start to go yellow with age!
#
configuration:
  start_date: 2005/08/21 00:00:00
  games_per_week: 7
